### PR TITLE
Browserstack

### PR DESCRIPTION
**Pull request by rosolko**

### CODE REVIEW

**Comment by asolntsev** [comment]
@rosolko What will we do with this PR? It has conflicts with master branch.

**Comment by rosolko** [comment]
@asolntsev from conflict points we need only customized `test` task, that allow to pass custom parameters:
```java
test {
  useJUnit()
  reports.junitXml.enabled = true
  reports.html.enabled = true
  testLogging.showStandardStreams = true
  systemProperties = System.properties + [
    'file.encoding'            : encoding,
    'java.util.logging.manager': 'org.apache.logging.log4j.jul.LogManager'
  ]
}
```

**Comment by asolntsev** [comment]
@rosolko I don't understand. Is this configuration needed always, or only for running tests on Browserstack?

Anyway, can you resolve the conflicts? Probably it's easier to create a new PR?

**Comment by rosolko** [comment]
@asolntsev Sorry, my bad. Only one part of config needed:
```
systemProperties = System.properties + [
    'file.encoding'            : encoding,
    'java.util.logging.manager': 'org.apache.logging.log4j.jul.LogManager'
  ]
```
And only for CI + browserstack run.

**Pull request closed without merging**
