### PR TITLE
Add scroll in mobile using scroll directions

### PR DESCRIPTION
**Pull request by amuthansakthivel**
## Proposed changes
Added code to scroll to element

```java
$(By.xpath(".//*[@text='Tabs']")).scrollTo().click(); //scroll max of 30 times in downward direction to find element
$(By.xpath(".//*[@text='Tabs']")).scroll(with(DOWN, 10)); //scroll max of 10 times in downward direction to find element
$(By.xpath(".//*[@text='Animation']")).scroll(up()); //scroll max of 30 times in upward direction to find element
```

## Checklist
- [x] Checkstyle and unit tests are passed locally with my changes by running `gradlew check` command
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by amuthansakthivel** [comment]
@asolntsev @BorisOsipov - Please help with the review.

**Comment by umesh-Ideahub** [comment]
Is this feature getting released anytime soon ? I have a scenario where I have to scroll to the bottom of the page to click an element. Is there any other way to do it in current version of the selenide-appium ? Thanks in advance

**Comment by amuthansakthivel** [comment]
> Is this feature getting released anytime soon ? I have a scenario where I have to scroll to the bottom of the page to click an element. Is there any other way to do it in current version of the selenide-appium ? Thanks in advance

For now, you can use it with custom commands like this - https://github.com/amuthansakthivel/SelenideAppiumFramework

@asolntsev - Please help with review

**Comment by umesh-Ideahub** [comment]
> > Is this feature getting released anytime soon ? I have a scenario where I have to scroll to the bottom of the page to click an element. Is there any other way to do it in current version of the selenide-appium ? Thanks in advance
> 
> For now, you can use it with custom commands like this - https://github.com/amuthansakthivel/SelenideAppiumFramework
> 
> @asolntsev - Please help with review

Thanks, worked great. Will use that until this one get released

**Review by asolntsev — APPROVED** [review]

**Pull request merged**
