### PR TITLE
Fix/#72 fix clipboard with wrapped webdriver

### PR DESCRIPTION
**Pull request by asolntsev**

### CODE REVIEW

**Review by BorisOsipov — APPROVED** [review]
It looks ok as temporary solution.

is AppiumElementDescriber out of scope? it seems this type check should be fixed too
https://github.com/selenide/selenide-appium/blob/master/src/main/java/com/codeborne/selenide/appium/AppiumElementDescriber.java#L59

**Comment by asolntsev** [comment]
Good point!
Should fix it as well.

**Comment by BorisOsipov** [comment]
@asolntsev this one type cast is still suspicions https://github.com/selenide/selenide-appium/blob/fix/%2372-fix-clipboard-with-wrapped-webdriver/src/main/java/com/codeborne/selenide/appium/AppiumElementDescriber.java#L126

**Comment by asolntsev** [comment]
@BorisOsipov Thank you, fixed it too.

**Pull request merged**
