### PR TITLE
Add capability to launch deep link url

### PR DESCRIPTION
**Pull request by amuthansakthivel**
## Proposed changes

Added capability to launch deep link URL from SelenideAppium class

## Checklist
- [x] Checkstyle and unit tests are passed locally with my changes by running `gradlew check` command
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by amuthansakthivel** [comment]
@BorisOsipov @asolntsev - I don't know why the tests have failed in CI or while running the ./gradlew command but passed when run from IDE.  Please advise.

**Comment by BorisOsipov** [comment]
@amuthansakthive l've added commit with hint why implementation is broken.

**Comment by amuthansakthivel** [comment]
> @amuthansakthive l've added commit with hint why implementation is broken.

@BorisOsipov Tests are failing again in CI

**Comment by BorisOsipov** [comment]
@amuthansakthivel sure it failed. I don't fix them. I make your test fails always to help you invesigate it. See https://github.com/selenide/selenide-appium/blob/main/src/main/java/com/codeborne/selenide/appium/WebdriverUnwrapper.java as advice.

**Comment by amuthansakthivel** [comment]
should I close this PR ? @BorisOsipov @asolntsev

**Comment by BorisOsipov** [comment]
@amuthansakthivel yes it is superseded by #100. I've cherry picked your changes and refactor the a bit. Please help with review.

**Pull request closed without merging**
